### ISSUE TITLE
upgrade gitstats

### ISSUE THREAD

**Issue by arnaudgelas** [InsightSoftwareConsortium/ITKSphinxExamples#19]
The version of gitstats we used is a fork of mine to be able to generate rst report. The fork is quite outdated with respect to upstream gitstats.
A first step would be to rebase these changes to latest gitstats version, then ultimately do a pull request to the upstream gitstats.

**Comment by tbirdso** [comment]
Resolved in [https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/commit/66cbdd66c72ec903c52f9be0c2963b69aa33a216](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/commit/66cbdd66c72ec903c52f9be0c2963b69aa33a216).
