### ISSUE TITLE
Rename ITKExamples repository to ITKSphinxExamples

### ISSUE THREAD

**Issue by aylward** [InsightSoftwareConsortium/ITKSphinxExamples#238]
Consider renaming to match the name and directory structure used within ITK

**Comment by thewtex** [comment]
- [ ] Repository renamed on GitHub
- [ ] Update naming references in ITKSphinxExamples repository
- [ ] Update naming references in the ITK
- [ ] Update naming references in the ITKSoftwareGuide repository
