### ISSUE TITLE
Update name of VTK components to be aware of VTK 9.0 changes.

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITKSphinxExamples#241]
```
CMake Deprecation Warning at /path/VTK-build/lib/cmake/vtk-9.0/vtk-config.cmake:71 (message):
  The new name for the 'vtkRenderingCore' component is 'RenderingCore'
```

This should be solved prepending `vtk` string to modules if the VTK version is less than 9.0

**Comment by thewtex** [comment]
@aylward @melrobin discussed running into this today, too.

**Comment by thewtex** [comment]
xref: https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/242
