### ISSUE TITLE
ITK build problems with Sphinx Examples

### ISSUE THREAD

**Issue by melrobin** [InsightSoftwareConsortium/ITKSphinxExamples#250]
When building ITK with BUILD_EXAMPLES and BUILD_DOCUMENTATION turned on I receive the following error:
CMake Error at Examples/SpatialObjects/CMakeLists.txt:27 (add_executable):
  add_executable cannot create target "LineSpatialObject" because another
  target with the same name already exists.  The existing target is an
  executable created in source directory
  "/home/melrobin/packages/ITK/Modules/Remote/SphinxExamples/src/Core/SpatialObjects/LineSpatialObject".
  See documentation for policy CMP0002 for more details.

There may be some conflict with ITKExamples.

**Comment by thewtex** [comment]
Perhaps we should rename the sphinx example to `CreateALineSpatialObject` or similar.
