### ISSUE TITLE
Fix bug in IterateRegionWithAccessToIndexWithoutWriteAccess

### ISSUE THREAD

**Issue by brad-t-moore** [InsightSoftwareConsortium/ITKSphinxExamples#270]
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/blob/fd2b39b4d652d89e9a7de53ea1c947cd8a597c30/src/Core/Common/IterateRegionWithAccessToIndexWithoutWriteAccess/Code.cxx#L54-L64

I'll submit a bug fix after I get my first PR through.  This ignores the set region and uses LargestPossibleRegion(), resulting in the entire image being output line per pixel during CI testing (in the logs).  Greatly clutters the CI logs.

**Comment by dzenanz** [comment]
I think there might be other instances of cluttering the logs.

**Comment by brad-t-moore** [comment]
Well, this one test takes up 80% of the entire log.

**Comment by dzenanz** [comment]
Uh-uh, I guess everyone before you was being fooled by this seemingly small region definition:
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/blob/fd2b39b4d652d89e9a7de53ea1c947cd8a597c30/src/Core/Common/IterateRegionWithAccessToIndexWithoutWriteAccess/Code.cxx#L45-L46

**Comment by brad-t-moore** [comment]
Yeah, I think it was meant to use that defined region, and another similarly named test uses the region correctly.
