### ISSUE TITLE
Published Documentation Does Not Match Build Date

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKSphinxExamples#333]
It seems like we are hosting three separate instances of ITKSphinxExamples HTML docs:

[https://itk.org/ITKExamples/](https://itk.org/ITKExamples/): v5.3.0, last updated Jun 16, 2021

[https://examples.itk.org/](https://examples.itk.org/): v5.2.0, last updated Feb 25, 2021

[https://6238eb96d5223a1c5aa1f18c--itkexamples.netlify.app/](https://6238eb96d5223a1c5aa1f18c--itkexamples.netlify.app/): v5.2.0, last updated March 21, 2022

Meanwhile, the last successful CI docs build on the `main` branch completed on March 21, 2022 and is expected to reflect version "v5.3.0". This is the version we are expecting to be hosted on one or all of the above instances.

The actual Github artifact associated with the run [https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/actions/runs/2017287524](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/actions/runs/2017287524): v5.2.0, last updated March 08, 2021

**Comment by tbirdso** [comment]
@dzenanz @thewtex Any thoughts on this one? Which of `itk.org/ITKExamples` vs `examples.itk.org` is correct? Do we have console access to the Netlify server to verify whether it is hosting multiple old documentation versions?

**Comment by tbirdso** [comment]
From discussion with @thewtex we determined:
- The most recent Netlify site is up to date: [https://6238eb96d5223a1c5aa1f18c--itkexamples.netlify.app/](https://6238eb96d5223a1c5aa1f18c--itkexamples.netlify.app/)
- `itk.examples.org` is possibly not being updated due to a conflict with how Netlify expects to build static web pages
- We will move from Netlify to Fleek for publishing the website and use the [https://github.com/FleekHQ/action-deploy](https://github.com/FleekHQ/action-deploy) Github Action to do so

**Comment by thewtex** [comment]
The Fleek publications will be available on https://itk-examples.on.fleek.co

Additional steps after the Fleek action is set up:

- Set up DNS to point https://examples.itk.org to Fleek.
- Add a redirect from itk.org/ITKExamples to examples.itk.org/

**Comment by thewtex** [comment]
Resolved via #341
