### ISSUE TITLE
Deploy To Netlify

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKSphinxExamples#341]
Moving from Netlify to Fleek for deployment.

Issues so far:
- no `.fleek.json` (added)
- `.fleek.json` in the wrong path (now copied to workspace root dir)
- cannot cd to `/home/runner/work/site` when setting `workDir` in CI steps (moved site to workspace root dir instead for container access)
- configuration error: 'siteId is required.' in path: /site/id [ [ [] ] ]

**Comment by tbirdso** [comment]
@thewtex Could you please provide the site ID that we should push to? This will be included in the `.fleek.json` file so that deployment can succeed.

See an example site ID in the Fleek deploy Github Actions repo: [.fleek.json](https://github.com/FleekHQ/action-deploy/blob/master/.fleek.json)

**Comment by tbirdso** [comment]
After discussion with @thewtex we are going back to Netlify. See git history for previous Netlify deployment step to get started.

**Comment by tbirdso** [comment]
@thewtex Could you please update what steps may be necessary for deployment via Netlify following #348?

I am unclear on what Netlify settings or other steps will need to be updated for each of the following to be automatically updated nightly:
1. [https://itk.org/ITKExamples/](https://itk.org/ITKExamples/) (currently the first search result for ITK Examples)
2. [https://examples.itk.org/](https://examples.itk.org/) (should redirect to the link above?)

**Comment by thewtex** [comment]
With #348, and an Apache redirect set up for https://itk.org/ITKExamples -> https://examples.itk.org/

Thanks for resolving this @tbirdso !
