### ISSUE TITLE
BUG: Example zip archive downloads are absent

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKSphinxExamples#373]
ZIP archives are absent from the server.

[https://examples.itk.org/src/filtering/convolution/colornormalizedcorrelation/ColorNormalizedCorrelation.zip](https://examples.itk.org/src/filtering/convolution/colornormalizedcorrelation/ColorNormalizedCorrelation.zip)

**Comment by PaulHax** [comment]
Another data point: In a local superbuild of the docs, the `src/filtering/convolution/colornormalizedcorrelation/` directory just has the build `Documentation.html` file.  The directory is *missing* the zip, source, and .rst files.

**Comment by thewtex** [comment]
At least the example I tested with Laryssa and Paul yesterday was working ...

**Comment by tbirdso** [comment]
Returning to investigate this issue, the examples in question are disabled in [`src/Filtering/Convolution/CMakeLists.txt`](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/blob/master/src/Filtering/Convolution/CMakeLists.txt) and therefore their archives are never built.

While issues with individual examples could be resolved so that archive builds are enabled, the more general solution would be to avoid adding a download link for pages whose directories are not added as targets via `add_example`.

**Comment by tbirdso** [comment]
Verified archives for the specified examples are now available for download on `examples.itk.org`

https://examples.itk.org/src/filtering/convolution/colornormalizedcorrelation/documentation
