### ISSUE TITLE
Retrieval of content file(s) failing

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKSphinxExamples#395]
### Description

`build-test-python-superbuild` and `build-test-documentation` CI builds are consistently failing since some time.
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/actions/workflows/build-test-publish.yml

It looks like there is a SHA512 content file that cannot be retrieved properly
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/runs/7933591657?check_suite_focus=true#step:8:8011

from https://insightsoftwareconsortium.github.io/ITKTestingData/SHA512

This results in a compiler error:
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/runs/7933591657?check_suite_focus=true#step:8:8029

However, the file does exist in https://data.kitware.com:443/api/v1/file/hashsum/SHA512/ (opening the link with the SHA512 checksum downloads the file).

### Additional Information

It is unclear to me the example to which the file corresponds (it is apparently named `OutputMeshes.png`), but the content link of the only file named as such
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/blob/master/src/Filtering/QuadEdgeMeshFiltering/ComputePlanarParameterizationOfAMesh/OutputMeshes.png.sha512

Also, it looks like the failing content file is not always the same:
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/393#issuecomment-1218543812

This is affecting the `master` branch and any PR that has been submitted lately.

**Comment by thewtex** [comment]
Addressed in #398

**Comment by jhlegarreta** [comment]
Closing as #398 has been merged.
