### ISSUE TITLE
Fix Broken Links on `examples.itk.org`

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKSphinxExamples#397]
Broken HTML archive download links at https://examples.itk.org/documentation/download/

**Comment by dzenanz** [comment]
@tbirdso was this fixed by #399?

**Comment by tbirdso** [comment]
@dzenanz Partially but not fully, the two "complete examples" archive links still lead to a "Page Not Found", will need to investigate further
